# Generated by Django 5.0.7 on 2024-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_blogpost_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
